name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradle

      - name: Build with Gradle
        run: ./gradle clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-jar
          path: build/libs/*.jar
